version: '3.8'

services:
  postgres:
    image: postgres:12.1
    restart: always
    ports:
      - 5432:5432
    network_mode: 'bridge'
    environment:
      - POSTGRES_DB=tutorial
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - $PWD/db_data:/var/lib/postgresql/data
